import {monitored,seed,type Evidence} from './radar-data';
import {classify,normalize,safeURL,canonicalURL} from './radar-model';
export type SourceStatus={id:string;title:string;url:string;ok:boolean;count:number;message:string};
export type Collection={fetchedAt:string;articles:Evidence[];statuses:SourceStatus[]};
const entities:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' ',aacute:'á',eacute:'é',iacute:'í',oacute:'ó',uacute:'ú',agrave:'à',egrave:'è',igrave:'ì',ograve:'ò',ugrave:'ù',acirc:'â',ecirc:'ê',icirc:'î',ocirc:'ô',ucirc:'û',atilde:'ã',otilde:'õ',ntilde:'ñ',ccedil:'ç',auml:'ä',euml:'ë',iuml:'ï',ouml:'ö',uuml:'ü',ndash:'–',mdash:'—',lsquo:'‘',rsquo:'’',ldquo:'“',rdquo:'”',hellip:'…'};
export function decode(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#(x[\da-f]+|\d+);/gi,(_,n)=>String.fromCodePoint(Math.min(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n),0x10ffff))).replace(/&([a-z]+);/gi,(full,name)=>{const ch=entities[name.toLowerCase()];return ch?(name[0]===name[0].toUpperCase()?ch.toUpperCase():ch):full})}
export function plain(s:string){return decode(s.replace(/<(script|style|nav|footer|header|aside)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function field(s:string,tag:string){return decode(s.match(new RegExp('<'+tag+'\\b[^>]*>([\\s\\S]*?)</'+tag+'>','i'))?.[1]||'')}
function dateOnly(s:string){if(!s)return null;const n=Date.parse(s.match(/^\d{4}-\d{2}-\d{2}/)?.[0]||s);return Number.isFinite(n)?new Date(n).toISOString().slice(0,10):null}
export function parseRSS(xml:string,source:string,observedAt:string):Evidence[]{const items=[...xml.matchAll(/<(?:item|entry)\b[^>]*>([\s\S]*?)<\/(?:item|entry)>/gi)];return items.slice(0,100).flatMap((m,i)=>{const item=m[1];const title=plain(field(item,'title')).slice(0,280);const url=safeURL(field(item,'link').trim()||item.match(/<link[^>]*href=["']([^"']+)/i)?.[1]||'');const summary=plain(field(item,'description')||field(item,'summary'));const found=classify(title+' '+summary.slice(0,650));const date=dateOnly(field(item,'pubDate')||field(item,'published')||field(item,'updated'));if(!url||!title||!found.length)return [];return [{id:'rss-'+canonicalURL(url),title,url,source,kind:'news',date,observedAt,topics:found,note:'Classificação automática por palavras-chave no título e na descrição do feed. Abra a fonte para conferir o contexto.',origin:'collected'} as Evidence]})}
async function limitedFetch(url:string){const r=await fetch(url,{headers:{Accept:'text/html,application/rss+xml,application/xml;q=0.9','User-Agent':'RadarEnem/1.0 (public educational source aggregator)'},signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw new Error('HTTP '+r.status);if(Number(r.headers.get('content-length'))>2_000_000)throw new Error('Resposta grande demais');const reader=r.body?.getReader();if(!reader)throw new Error('Sem conteúdo');const chunks:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>2_000_000){await reader.cancel();throw new Error('Resposta grande demais')}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}return new TextDecoder().decode(bytes)}
export async function collect():Promise<Collection>{const fetchedAt=new Date().toISOString();const observedAt=fetchedAt.slice(0,10);const outputs=await Promise.all(monitored.map(async s=>{try{const body=await limitedFetch(s.url);let articles:Evidence[]=[];
 if(s.format==='rss'){if(!/<(?:rss|feed)\b/i.test(body))throw new Error('Feed não reconhecido');articles=parseRSS(body,s.title,observedAt)}
 else {const main=body.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1]||body.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]||body;const text=plain(main);if(text.length<400||!normalize(text).includes('2026'))throw new Error('Conteúdo esperado não encontrado');const base=seed.find(e=>e.id===s.id)!;const headings=[...main.matchAll(/<h[23]\b[^>]*>([\s\S]*?)<\/h[23]>/gi)].map(m=>plain(m[1])).filter(t=>/^\d+[.)]|^eixo\s/i.test(t));const found=classify(headings.length?headings.join(' '):text.slice(0,16000));if(!found.length)throw new Error('Nenhum tema reconhecido');const published=body.match(/"datePublished"\s*:\s*"([^"]+)"/i)?.[1]||'';articles=[{...base,date:dateOnly(published)||base.date,observedAt,topics:found,origin:'collected',note:'Página consultada nesta coleta. Temas identificados por palavras-chave; confira a fonte. A data original, quando identificada, determina o peso.'}]}
 return {articles,status:{id:s.id,title:s.title,url:s.url,ok:true,count:articles.length,message:articles.length?'Consulta concluída':'Consulta concluída, sem matérias compatíveis no feed atual'} as SourceStatus};
 }catch(e){return {articles:[],status:{id:s.id,title:s.title,url:s.url,ok:false,count:0,message:e instanceof Error?(e.name==='TimeoutError'||e.name==='AbortError'?'A fonte demorou a responder':e.message==='fetch failed'?'A fonte não respondeu':e.message):'Não foi possível consultar'} as SourceStatus}}}));const seen=new Set<string>();return {fetchedAt,articles:outputs.flatMap(x=>x.articles).filter(e=>{const key=canonicalURL(e.url);if(seen.has(key))return false;seen.add(key);return true}),statuses:outputs.map(x=>x.status)}}
