import {historical, topics, type Evidence, type Kind} from './radar-data';

export type Weights = {editorial:number;news:number;history:number;institutional:number;hint:number};
export const defaultWeights:Weights = {editorial:50,news:25,history:10,institutional:10,hint:5};
export const weightKeys = ['editorial','news','history','institutional','hint'] as const;
export const normalize = (s:string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
export function safeURL(s:string){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.toString():''}catch{return ''}}
export function canonicalURL(s:string){try{const u=new URL(s);u.hash='';for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_')||k==='fbclid'||k==='gclid')u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return ''}}
export function publisher(s:string){try{const h=new URL(s).hostname.replace(/^www\./,'');if(h==='gov.br'||h.endsWith('.gov.br'))return 'gov.br';if(h.endsWith('.uol.com.br'))return 'uol.com.br';const a=h.split('.');return h.endsWith('.com.br')?a.slice(-3).join('.'):a.slice(-2).join('.')}catch{return 'sem-fonte'}}
export function classify(s:string){const text=normalize(s);return topics.filter(t=>t.keywords.some(k=>text.includes(k))).map(t=>t.id)}
export function deduplicate(evidence:Evidence[]){const seen=new Set<string>();return evidence.filter(e=>{const key=canonicalURL(e.url)||normalize(e.title);if(seen.has(key))return false;seen.add(key);return true})}
export function validDay(s:unknown):s is string{return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s}
export function eligible(e:Evidence,cutoff:string){if(!validDay(cutoff))return false;const date=e.date||e.observedAt;if(!validDay(date))return false;const end=Date.parse(cutoff+'T23:59:59Z');const d=Date.parse(date+'T00:00:00Z');return d<=end&&(e.date?end-d<731*86400000:true)}
export function freshness(e:Evidence,cutoff:string){if(!eligible(e,cutoff))return 0;if(!e.date)return .5;const days=Math.max(0,(Date.parse(cutoff)-Date.parse(e.date))/86400000);return Math.pow(.5,days/180)}
function strength(evidence:Evidence[],kind:Kind,cutoff:string){const groups=new Map<string,number>();for(const e of evidence.filter(e=>e.kind===kind)){const group=publisher(e.url);const factor=freshness(e,cutoff);groups.set(group,Math.max(groups.get(group)||0,factor))}return Math.min(1,[...groups.values()].reduce((a,b)=>a+b,0)/3)}
export function sanitizeWeights(input:unknown):Weights{const w=input as Partial<Weights>|null;const result={...defaultWeights};for(const k of weightKeys){const value=w?.[k];if(typeof value==='number'&&Number.isFinite(value))result[k]=Math.max(0,Math.min(k==='hint'?5:k==='institutional'?15:100,value));}return result}
export function rank(evidence:Evidence[],weights:Weights=defaultWeights,includeHints=false,cutoff='2026-09-30',includeInstitutional=true){
 const clean=deduplicate(evidence).filter(e=>eligible(e,cutoff));const past=historical.filter(h=>h[0]<Number(cutoff.slice(0,4)));const counts=new Map<string,number>();for(const h of past)counts.set(h[2],(counts.get(h[2])||0)+1);const max=Math.max(1,...counts.values())+1;
 const w=sanitizeWeights(weights);
 const rows=topics.map(t=>{const related=clean.filter(e=>e.topics.includes(t.id)&&(includeHints||e.kind!=='hint')&&(includeInstitutional||e.kind!=='institutional'));const factors={editorial:strength(related,'editorial',cutoff),news:strength(related,'news',cutoff),history:((counts.get(t.axis)||0)+1)/max,institutional:includeInstitutional?strength(related,'institutional',cutoff):0,hint:includeHints?strength(related,'hint',cutoff):0};const points={editorial:w.editorial*factors.editorial,news:w.news*factors.news,history:w.history*factors.history,institutional:w.institutional*factors.institutional,hint:w.hint*factors.hint};const score=10+Object.values(points).reduce((a,b)=>a+b,0);return {...t,score,factors,points,related,groups:new Set(related.map(e=>publisher(e.url))).size,historical:past.filter(h=>h[2]===t.axis)};}).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));
 const total=rows.reduce((a,b)=>a+b.score,0);const raw=rows.map(r=>r.score/total*1000);const units=raw.map(Math.floor);let remaining=1000-units.reduce((a,b)=>a+b,0);const indices=raw.map((v,i)=>({i,remainder:v-units[i]})).sort((a,b)=>b.remainder-a.remainder);for(const {i} of indices){if(remaining--<=0)break;units[i]++}return rows.map((r,i)=>({...r,percent:units[i]/10}));
}
export function validEvidence(x:unknown):x is Evidence{if(!x||typeof x!=='object')return false;const e=x as Evidence;return typeof e.id==='string'&&e.id.length<=2500&&typeof e.title==='string'&&e.title.length>=1&&e.title.length<=300&&typeof e.url==='string'&&e.url.length<=2500&&(!e.url||!!safeURL(e.url))&&typeof e.source==='string'&&e.source.length<=250&&['editorial','news','institutional','hint'].includes(e.kind)&&validDay(e.observedAt)&&(e.date===null||validDay(e.date))&&Array.isArray(e.topics)&&e.topics.length<=topics.length&&e.topics.every(t=>topics.some(p=>p.id===t))&&typeof e.note==='string'&&e.note.length<=2000&&['curated','collected','personal'].includes(e.origin)}
