export const BASE_DATE = '2026-09-30';
export type Kind = 'editorial' | 'news' | 'institutional' | 'hint';
export type Evidence = {id:string;title:string;url:string;source:string;kind:Kind;date:string|null;observedAt:string;topics:string[];note:string;origin:'curated'|'collected'|'personal'};
export type Topic = {id:string;title:string;axis:string;keywords:string[];proposal:string;angles:string[]};
export const topics: Topic[] = [
 {id:'leitura',title:'Leitura, livros e formação de leitores',axis:'Educação e cultura',keywords:['formacao de leitores','habito de leitura','ensino da leitura','pratica de leitura','acesso ao livro','bibliotecas','letramento','leitura como pratica social'],proposal:'Desafios para democratizar o acesso à leitura e formar leitores no Brasil',angles:['Bibliotecas, acesso a livros e desigualdades territoriais','Leitura como prática social e responsabilidade de toda a escola']},
 {id:'digital',title:'Proteção de crianças no ambiente digital',axis:'Infância e juventude',keywords:['eca digital','protecao de criancas','criancas e adolescentes no ambiente','infancia digital','adultizacao','publicidade infantil'],proposal:'Caminhos para proteger crianças e adolescentes nos ambientes digitais brasileiros',angles:['Responsabilidade das plataformas e publicidade direcionada','Educação digital na escola e mediação das famílias']},
 {id:'clima',title:'Crise climática e cidades vulneráveis',axis:'Meio ambiente',keywords:['climatic','plano clima','enchent','desastres','degradacao ambiental','racismo ambiental','aquecimento global'],proposal:'Desafios para proteger populações vulneráveis dos desastres climáticos no Brasil',angles:['Prevenção de desastres e desigualdade territorial','Moradia segura e adaptação das cidades']},
 {id:'mental',title:'Saúde mental e hiperconexão',axis:'Saúde',keywords:['saude mental','doencas mentais','hiperconect','era das telas','dependencia digital','ansiedade'],proposal:'Desafios para o cuidado com a saúde mental de jovens em uma sociedade hiperconectada',angles:['Pressão por desempenho e comparação nas redes','Acolhimento nas escolas e acesso à atenção psicossocial']},
 {id:'ia',title:'Inteligência artificial e desinformação',axis:'Tecnologia e informação',keywords:['inteligencia artificial','desinformacao','fake news','deepfake','letramento midiatico','poluicao informacional'],proposal:'Caminhos para enfrentar a desinformação amplificada pela inteligência artificial no Brasil',angles:['Educação midiática e verificação de informações','Transparência das plataformas e responsabilidade pelo conteúdo']},
 {id:'inclusao',title:'Inclusão de pessoas com deficiência e neurodivergentes',axis:'Diversidade e direitos',keywords:['neurodivergen','capacitismo','altas habilidades','superdotacao','pessoas com deficiencia','educacao inclusiva','autismo','acessibilidade'],proposal:'Desafios para garantir a participação social das pessoas neurodivergentes no Brasil',angles:['Barreiras na educação e no trabalho','Acessibilidade e combate a estereótipos']},
 {id:'educacao',title:'Alfabetização e desigualdade educacional',axis:'Educação e cultura',keywords:['alfabetizacao','analfabetismo','evasao escolar','abandono escolar','desigualdade educacional','tecnologia, escola','violencia escolar'],proposal:'Caminhos para garantir a alfabetização plena e reduzir desigualdades educacionais no Brasil',angles:['Permanência escolar e formação de professores','Educação de jovens e adultos e acesso às tecnologias']},
 {id:'trabalho',title:'Trabalho, informalidade e proteção social',axis:'Trabalho',keywords:['trabalho escravo','precarizacao','informalidade','protecao social','relacoes de trabalho','trabalho no seculo','uberizacao'],proposal:'Desafios para garantir trabalho digno diante das novas relações de emprego no Brasil',angles:['Proteção social de trabalhadores de plataformas','Qualificação profissional e enfrentamento da exploração']},
 {id:'genero',title:'Violência de gênero e invisibilidade feminina',axis:'Diversidade e direitos',keywords:['misoginia','violencia contra a mulher','mulheres cientistas','mulheres na ciencia','trabalho de cuidado','desigualdade de genero','violencia de genero'],proposal:'Caminhos para enfrentar a violência de gênero e a radicalização nos ambientes digitais',angles:['Naturalização da violência e reprodução de estereótipos','Redes de proteção e responsabilização']},
 {id:'moradia',title:'Moradia e população em situação de rua',axis:'Cidadania e sociedade',keywords:['situacao de rua','deficit habitacional','gentrificacao','direito a moradia','habitacao'],proposal:'Desafios para assegurar moradia digna e proteção social à população em situação de rua',angles:['Acesso à habitação e serviços públicos','Invisibilidade social e políticas de acolhimento']},
 {id:'ciencia',title:'Ciência, saúde pública e automedicação',axis:'Saúde',keywords:['automedicacao','confianca na ciencia','instituicoes de saude','educacao em saude','vacinas','alcoolismo','padroes esteticos','saude publica e comportamento'],proposal:'Caminhos para fortalecer a confiança na ciência e a informação responsável em saúde no Brasil',angles:['Divulgação científica acessível','Desinformação sobre tratamentos e riscos da automedicação']},
 {id:'juventude',title:'Violência e oportunidades para a juventude',axis:'Infância e juventude',keywords:['futuro da juventude','violencia letal','violencia escolar','protecao da infancia','violencia sexual contra','criancas em situacao'],proposal:'Desafios para garantir segurança e oportunidades à juventude brasileira',angles:['Desigualdade no acesso à educação e ao primeiro emprego','Prevenção da violência e participação dos jovens']},
 {id:'democracia',title:'Participação social e cidadania',axis:'Cidadania e sociedade',keywords:['participacao social','sistema democratico','participacao politica','registro civil','acesso a cidadania'],proposal:'Caminhos para ampliar a participação social na construção de políticas públicas brasileiras',angles:['Acesso à informação e espaços de participação','Desigualdade de representação e pertencimento']},
 {id:'idosos',title:'Envelhecimento e combate ao etarismo',axis:'Diversidade e direitos',keywords:['idoso','envelhecimento','etarismo','brasil que envelhece','populacao idosa'],proposal:'Desafios para promover autonomia e inclusão da população idosa no Brasil',angles:['Acessibilidade e redes de cuidado','Combate à discriminação por idade']},
 {id:'cultura',title:'Diversidade cultural e povos tradicionais',axis:'Educação e cultura',keywords:['povos tradicionais','povos indigenas','heranca africana','patrimonio cultural','diversidade cultural','acesso a cultura','intolerancia religiosa'],proposal:'Desafios para preservar o patrimônio cultural de comunidades tradicionais brasileiras',angles:['Valorização dos saberes e combate ao apagamento cultural','Acesso a políticas culturais e participação das comunidades']},
 {id:'fome',title:'Segurança alimentar e desigualdade',axis:'Cidadania e sociedade',keywords:['inseguranca alimentar','combate a fome','seguranca alimentar','desperdicio de alimentos'],proposal:'Caminhos para garantir segurança alimentar à população brasileira',angles:['Desigualdade de renda e acesso a alimentos','Produção, distribuição e desperdício']},
 {id:'acesso',title:'Inclusão digital e acesso à informação',axis:'Tecnologia e informação',keywords:['inclusao digital','exclusao digital','acesso a internet','usuarios da internet','desigualdade digital','domicilios com internet'],proposal:'Desafios para ampliar a inclusão digital e o acesso qualificado à informação no Brasil',angles:['Infraestrutura e desigualdades regionais','Formação para o uso autônomo de serviços digitais']},
];
export const historical = [
 [1998,'Aprender e viver','Educação e cultura'],[1999,'Exercício da cidadania','Cidadania e sociedade'],[2000,'Direitos de crianças e adolescentes','Infância e juventude'],[2001,'Desenvolvimento e preservação ambiental','Meio ambiente'],[2002,'Voto e transformação social','Cidadania e sociedade'],[2003,'Enfrentamento da violência','Cidadania e sociedade'],[2004,'Liberdade de informação e seus limites','Tecnologia e informação'],[2005,'Combate ao trabalho infantil','Infância e juventude'],[2006,'Leitura como transformação','Educação e cultura'],[2007,'Convivência com as diferenças','Diversidade e direitos'],[2008,'Preservação da Amazônia','Meio ambiente'],[2009,'Indivíduo e ética','Cidadania e sociedade'],[2010,'Trabalho e dignidade','Trabalho'],[2011,'Privacidade na vida em rede','Tecnologia e informação'],[2012,'Imigração para o Brasil','Diversidade e direitos'],[2013,'Impactos da Lei Seca','Saúde'],[2014,'Publicidade para crianças','Infância e juventude'],[2015,'Violência contra mulheres','Diversidade e direitos'],[2016,'Intolerância religiosa','Diversidade e direitos'],[2017,'Educação de pessoas surdas','Educação e cultura'],[2018,'Dados digitais e manipulação de comportamento','Tecnologia e informação'],[2019,'Acesso ao cinema','Educação e cultura'],[2020,'Estigma das doenças mentais','Saúde'],[2021,'Registro civil e cidadania','Cidadania e sociedade'],[2022,'Comunidades e povos tradicionais','Educação e cultura'],[2023,'Invisibilidade do cuidado realizado por mulheres','Trabalho'],[2024,'Valorização da herança africana','Educação e cultura'],[2025,'Perspectivas acerca do envelhecimento na sociedade brasileira','Diversidade e direitos'],
] as const;
export const historySource = 'https://querobolsa.com.br/revista/veja-todos-os-temas-de-redacao-do-enem-desde-1998';
export const officialSource = 'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/provas-e-gabaritos';
export const guidanceSource = 'https://www.gov.br/inep/pt-br/centrais-de-conteudo/noticias/enem/enem-2026-cartilha-da-redacao-esta-disponivel';
export const seed:Evidence[] = [
 {id:'pnd-leitura',title:'PND 2026: leitura como responsabilidade de toda a escola',url:'https://noticias.institutodering.com.br/2026/09/21/leitura-e-tema-do-pnd/',source:'Instituto Dering / análise da PND',kind:'institutional',date:'2026-09-21',observedAt:BASE_DATE,topics:['leitura','educacao'],note:'Análise pública do Instituto Dering descreve uma questão discursiva sobre o ensino da leitura em todas as áreas. A publicação dos cadernos foi confirmada pelo Inep em 24/09. A interpretação é do professor; a possível relação com o Enem é uma hipótese, sem validação preditiva.',origin:'curated'},
 {id:'fgv',title:'Possíveis temas de redação para 2026 — FGV',url:'https://vestibular.fgv.br/blog/redacao-do-enem-2026-possiveis-temas',source:'FGV',kind:'editorial',date:'2026-05-05',observedAt:BASE_DATE,topics:['educacao','ia','mental','trabalho','ciencia','idosos'],note:'Sugere tecnologia na educação, cidadania digital, saúde mental, trabalho, informação em saúde e envelhecimento. Data de publicação obtida nos metadados da página.',origin:'curated'},
 {id:'brasil-escola',title:'Quinze propostas de professores para o Enem 2026',url:'https://vestibular.brasilescola.uol.com.br/enem/15-temas-redacao-enem-2026.htm',source:'Brasil Escola',kind:'editorial',date:'2026-05-06',observedAt:BASE_DATE,topics:['clima','digital','ciencia','genero','moradia','ia','educacao','trabalho','democracia','mental','juventude'],note:'Reúne apostas docentes sobre clima, infância online, informação, desigualdades e saúde. Opiniões de preparação; nenhuma confirmação do tema.',origin:'curated'},
 {id:'cnn',title:'Sete eixos de preparação apontados por professor',url:'https://www.cnnbrasil.com.br/educacao/redacao-do-enem-professor-aponta-7-temas-que-merecem-atencao-em-2026/',source:'CNN Brasil / Ademar Celedônio',kind:'editorial',date:'2026-08-16',observedAt:BASE_DATE,topics:['digital','juventude','educacao','ciencia','inclusao','clima'],note:'Indica proteção online, juventude, alfabetização, confiança científica, altas habilidades, neurodivergência e ambiente como assuntos para estudar.',origin:'curated'},
 {id:'mdh-digital',title:'ECA Digital: orientações de proteção no ambiente online',url:'https://www.gov.br/mdh/pt-br/assuntos/noticias/2026/defeso-eleitoral/agosto/eca-digital-conheca-as-regras-de-protecao-de-criancas-e-adolescentes-no-ambiente-online',source:'Ministério dos Direitos Humanos',kind:'news',date:'2026-08-21',observedAt:BASE_DATE,topics:['digital'],note:'Publicação sobre proteção de crianças e adolescentes no ambiente digital. Contexto social, sem indicação sobre a prova.',origin:'curated'},
 {id:'anpd-digital',title:'ANPD aborda um ano do ECA Digital',url:'https://www.gov.br/anpd/pt-br/assuntos/noticias/eca-digital-completa-um-ano-e-e-marco-na-protecao-de-criancas-e-adolescentes-na-internet',source:'ANPD',kind:'news',date:'2026-09-16',observedAt:BASE_DATE,topics:['digital'],note:'Balanço da proteção de menores na internet. Agrupado com gov.br para limitar repetição institucional.',origin:'curated'},
 {id:'plano-clima',title:'Planejamento participa da construção do Plano Clima',url:'https://www.gov.br/planejamento/pt-br/assuntos/noticias/2026/marco/ministerio-do-planejamento-e-orcamento-tem-participacao-ativa-na-construcao-do-plano-clima',source:'Ministério do Planejamento',kind:'news',date:'2026-03-19',observedAt:BASE_DATE,topics:['clima'],note:'Apresentação de planejamento climático e discussão de financiamento. É atualidade, não aposta do Inep.',origin:'curated'},
 {id:'ibge-internet',title:'IBGE divulga uso da internet pela população em 2025',url:'https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/47408-proporcao-de-usuarios-da-internet-no-pais-ultrapassou-90-da-populacao-de-10-anos-ou-mais-em-2025',source:'IBGE',kind:'news',date:null,observedAt:BASE_DATE,topics:['acesso'],note:'Dados de acesso à internet e diferenças regionais. Data exata de publicação não identificada nesta base; recebe peso reduzido.',origin:'curated'},
];
export const monitored = [
 ...seed.filter(x=>x.kind!=='institutional').map(x=>({id:x.id,title:x.source,url:x.url,format:'html' as const,kind:x.kind})),
 {id:'agencia-brasil',title:'Agência Brasil — últimas notícias',url:'https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml',format:'rss' as const,kind:'news' as Kind},
];

export const pndSource = 'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/prova-nacional-docente/provas-e-gabaritos';
export const pndNews = 'https://www.gov.br/inep/pt-br/centrais-de-conteudo/noticias/prova-nacional-docente/inep-divulga-gabaritos-preliminares-da-pnd';
export const pnd2026PDF = 'https://download.inep.gov.br/pnd/provas_e_gabaritos/2026_pedagogia_PV_1.pdf';
export const pnd2025PDF = 'https://download.inep.gov.br/pnd/provas_e_gabaritos/2025_pedagogia_PV_1.pdf';
export const officialDocuments = [
 {id:'cartilha',year:2026,type:'Orientações',title:'Cartilha de redação do Enem 2026',description:'Competências, orientações e redações comentadas. Referência para escrever e revisar seu texto.',url:'https://www.gov.br/inep/pt-br/centrais-de-conteudo/acervo-linha-editorial/publicacoes-institucionais/avaliacoes-e-exames-da-educacao-basica/a-redacao-do-enem-2026-cartilha-do-a-participante',tag:'ENEM',scope:'Preparação oficial; não indica o próximo tema.'},
 {id:'enem-provas',year:null,type:'Acervo',title:'Provas e gabaritos do Enem',description:'Cadernos por edição para conferir as propostas e os textos motivadores na fonte original.',url:officialSource,tag:'ENEM',scope:'Inclui modalidades que não entram na série regular deste radar.'},
 {id:'pnd-provas',year:2026,type:'Acervo',title:'Prova Nacional Docente: cadernos e correção',description:'Acesse os materiais de 2026 e de 2025. A PND tem objetivos e público diferentes do Enem.',url:pndSource,tag:'PND',scope:'Documento público de outra avaliação; relação temática é hipótese.'},
 {id:'pnd26',year:2026,type:'PDF',title:'PND 2026 — Pedagogia, tipo 1',description:'Caderno oficial com formação geral docente e parte específica. Veja a questão discursiva no início.',url:pnd2026PDF,tag:'PND',scope:'Link localizado no acervo oficial em 30/09/2026.'},
 {id:'pnd25',year:2025,type:'PDF',title:'PND 2025 — Pedagogia, tipo 1',description:'Caderno para consultar o antecedente sobre idadismo discutido no dossiê.',url:pnd2025PDF,tag:'PND',scope:'Um antecedente não estabelece um padrão de previsão.'},
 {id:'pnd-release',year:2026,type:'Notícia',title:'Inep divulga cadernos e gabaritos da PND',description:'Publicação de 24/09/2026 confirma a disponibilidade dos cadernos e da grade de correção.',url:pndNews,tag:'INEP',scope:'Confirmação da publicação dos materiais, não do tema do Enem.'},
] as const;
