import assert from 'node:assert/strict';
import {loadRadar} from './compile-radar.mjs';
const {model:m,data:d,collector:c}=await loadRadar();
const baseline=m.rank(d.seed,m.defaultWeights,false,d.BASE_DATE,true);
assert.equal(baseline.length,17);
assert.equal(Math.round(baseline.reduce((a,r)=>a+r.percent,0)*10),1000);
assert.ok(baseline.every(r=>Number.isFinite(r.score)&&r.percent>0));
const without=m.rank(d.seed,m.defaultWeights,false,d.BASE_DATE,false);
assert.ok(baseline.find(r=>r.id==='leitura').score>without.find(r=>r.id==='leitura').score);
assert.equal(without.find(r=>r.id==='leitura').points.institutional,0);
const hint={...d.seed[0],id:'hint-test',url:'https://example.org/hint',kind:'hint',topics:['leitura']};
assert.deepEqual(m.rank([...d.seed,hint],m.defaultWeights,false,d.BASE_DATE),baseline);
assert.ok(m.rank([hint],{...m.defaultWeights,hint:999},true,d.BASE_DATE).find(r=>r.id==='leitura').points.hint<=5);
assert.ok(m.rank(d.seed,{...m.defaultWeights,institutional:999},false,d.BASE_DATE).every(r=>r.points.institutional<=15));
assert.equal(m.deduplicate([d.seed[0],{...d.seed[0],url:d.seed[0].url+'?utm_source=test#x'}]).length,1);
assert.equal(m.eligible({...hint,date:'2026-10-01'},d.BASE_DATE),false);
assert.equal(m.eligible({...hint,date:'2020-01-01'},d.BASE_DATE),false);
assert.equal(m.validDay('2026-02-30'),false);
assert.equal(m.safeURL('javascript:alert(1)'), '');
assert.equal(m.safeURL('https://user:pass@example.org'), '');
assert.equal(m.validEvidence({...hint,date:'2026-02-30'}),false);
assert.equal(m.sanitizeWeights({editorial:NaN,institutional:999,hint:999}).institutional,15);
assert.equal(m.sanitizeWeights({editorial:NaN}).editorial,m.defaultWeights.editorial);
const xml='<rss><channel><item><title>Forma&ccedil;&atilde;o de leitores e bibliotecas</title><link>https://example.org/leitura</link><description>Ensino da leitura como pr&aacute;tica social</description><pubDate>Wed, 30 Sep 2026 12:00:00 GMT</pubDate></item></channel></rss>';
const items=c.parseRSS(xml,'Teste',d.BASE_DATE);
assert.equal(items.length,1);assert.ok(items[0].topics.includes('leitura'));assert.equal(items[0].date,d.BASE_DATE);assert.ok(m.validEvidence(items[0]));
console.log('Regras verificadas: total de 100%, cenário PND, limites de pistas, duplicatas, datas, URLs e feed de leitura.');
